// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eoijpfajhiflkkezbkag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvaWpwZmFqaGlmbGtrZXpia2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMzk1NjcsImV4cCI6MjA2NzkxNTU2N30.NCXGVHdC318z93V8iRyseEIRWTqD82HyxqfWvV9GCV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});